/**:
  ros__parameters:
    # Mocap relay parameters
    asset_name: mocap_camera
    tracked_objects: [
      ramp1,
      ramp2,
      block1,
      block2,
      block3,
    ]

    # VRPN parameters
    server: 192.168.0.241
    port: 3883
    update_frequency: 360.0
    frame_id: map
    use_server_time: false
    broadcast_tf: true

    # Odometry parameters
    filter_alpha: 0.2
